% -------------------------------------------------------------------
%  Generated by MATLAB on 19-Jun-2020 10:33:20
%  MATLAB version: 9.7.0.1190202 (R2019b)
% -------------------------------------------------------------------
saveVarsMat = load('dane365.mat');

data = saveVarsMat.data; % <2302x1 double> too many elements

time = saveVarsMat.time; % <1x1 datetime> unsupported class

clear saveVarsMat;
