function [celcjusz] = importRaport_Pomiarow(workbookFile, sheetName, dataLines)
%IMPORTFILE2 Import data from a spreadsheet
%  [VARNAME1, VARNAME2, VARNAME3, KODPRBKI, MIEJSCEPOBORU, DATAPOBORU,
%  GODZINAPOBORU, PRBOBIORCA, WYNIK] = IMPORTFILE2(FILE) reads data from
%  the first worksheet in the Microsoft Excel spreadsheet file named
%  FILE.  Returns the data as column vectors.
%
%  [VARNAME1, VARNAME2, VARNAME3, KODPRBKI, MIEJSCEPOBORU, DATAPOBORU,
%  GODZINAPOBORU, PRBOBIORCA, WYNIK] = IMPORTFILE2(FILE, SHEET) reads
%  from the specified worksheet.
%
%  [VARNAME1, VARNAME2, VARNAME3, KODPRBKI, MIEJSCEPOBORU, DATAPOBORU,
%  GODZINAPOBORU, PRBOBIORCA, WYNIK] = IMPORTFILE2(FILE, SHEET,
%  DATALINES) reads from the specified worksheet for the specified row
%  interval(s). Specify DATALINES as a positive scalar integer or a
%  N-by-2 array of positive scalar integers for dis-contiguous row
%  intervals.
%
%  Example:
%  [VarName1, VarName2, VarName3, Kodprbki, Miejscepoboru, Datapoboru, Godzinapoboru, Prbobiorca, Wynik] = importfile2('P:\git\Ekonometria\Wod20\Raport_Pomiarow.xls', '2019', [6, 348]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Apr-2020 09:49:11

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
     % check workbook data length
    tmp = readtable(workbookFile,'Sheet', sheetName, 'PreserveVariableNames', true);    
    heighT = size(tmp,1)-6;
    if (heighT > 6)
        dataLines = [6, heighT]; 
    else
        dataLines = [6, 348];    
    end
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":I" + dataLines(1, 2);

% Specify file level properties
% opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify column names and types
opts.VariableNames = ["Lp", "Data", "Godz", "Probka", "Miejscepoboru", "Datapoboru", "Godzinapoboru", "Prbobiorca", "Wynik"];
opts.VariableTypes = ["double", "string", "string", "string", "categorical", "string", "categorical", "categorical", "string"];

% Specify variable properties
opts = setvaropts(opts, [ "Data", "Godz", "Probka", "Datapoboru"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Lp", "Data", "Godz", "Probka", "Miejscepoboru", "Datapoboru", "Godzinapoboru", "Prbobiorca", "Wynik"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Lp", "Godz"], "TreatAsMissing", '');
% Import the data
celcjusz = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":I" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    celcjusz = [celcjusz; tb]; %#ok<AGROW>
end

end